### ISSUE TITLE
Crash site with elementor pro 2.9.1 and I cannot to edit page

### ISSUE THREAD

**Issue by darek29** [dbjpanda/actions-pack-issue-tracker#15] opened 2020-03-19 11:32 UTC
With version elementor pro 2.8.5 and elementor 2.9.6 is working correctly.

I have problem when i update to version elementor pro 2.9.1.
The page does not display correctly, the popups do not open and I can not to edit page with elementor.

Below is the error from website:

Fatal error: Uncaught Error: Class 'ElementorPro\Classes\Utils' not found in C:\xampp\htdocs\testsite\wp-content\plugins\actions-pack-premium\actions\register.php:231 Stack trace: #0 C:\xampp\htdocs\testsite\wp-content\plugins\elementor-pro\modules\forms\widgets\form.php(727): Action_Register->register_settings_section(Object(ElementorPro\Modules\Forms\Widgets\Form)) #1 C:\xampp\htdocs\testsite\wp-content\plugins\elementor\includes\base\controls-stack.php(1946): ElementorPro\Modules\Forms\Widgets\Form->_register_controls() #2 C:\xampp\htdocs\testsite\wp-content\plugins\elementor\includes\base\controls-stack.php(498): Elementor\Controls_Stack->init_controls() #3 C:\xampp\htdocs\testsite\wp-content\plugins\elementor\includes\base\widget-base.php(150): Elementor\Controls_Stack->get_stack() #4 C:\xampp\htdocs\testsite\wp-content\plugins\elementor\includes\base\controls-stack.php(291): Elementor\Widget_Base->get_stack() #5 C:\xampp\htdocs\testsite\wp-content\plugins\elementor\includes\base\controls-stack.php(2001): Elementor\C in C:\xampp\htdocs\testsite\wp-content\plugins\actions-pack-premium\actions\register.php on line 231

**Comment by dbjpanda** [comment] 2020-03-19 15:59
Duplicate of #14

**Closed by dbjpanda** 2020-03-19 15:59 UTC
